# Generated by Django 4.1.1 on 2022-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0002_cat_delete_catering'),
    ]

    operations = [
        migrations.CreateModel(
            name='mov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('thadd', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('yadd', models.CharField(max_length=200)),
                ('ycity', models.CharField(max_length=200)),
                ('yzip', models.CharField(max_length=200)),
                ('phnum', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
