# Generated by Django 4.1.1 on 2022-11-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0003_mov'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mov',
            new_name='movi',
        ),
    ]
