# Generated by Django 4.1.1 on 2022-11-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0004_rename_mov_movi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movi',
            old_name='busname',
            new_name='busname1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='city',
            new_name='city1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='phnum',
            new_name='phnum1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='price',
            new_name='price1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='thadd',
            new_name='thadd1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='yadd',
            new_name='yadd1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='ycity',
            new_name='ycity1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='yzip',
            new_name='yzip1',
        ),
        migrations.RenameField(
            model_name='movi',
            old_name='zip',
            new_name='zip1',
        ),
    ]
