# Generated by Django 4.1.1 on 2022-11-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0005_rename_busname_movi_busname1_rename_city_movi_city1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('thadd', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('yaddress', models.CharField(max_length=200)),
                ('ycity', models.CharField(max_length=200)),
                ('yzip', models.CharField(max_length=200)),
                ('phnum', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='movi',
        ),
    ]
