# Generated by Django 4.1.1 on 2022-11-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0006_movie_delete_movi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='phnum',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='yaddress',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ycity',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='yzip',
        ),
    ]
