# Generated by Django 4.1.1 on 2022-11-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0007_remove_movie_email_remove_movie_phnum_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
