# Generated by Django 4.1.1 on 2022-11-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0009_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conname', models.CharField(max_length=200)),
                ('nameor', models.CharField(max_length=200)),
                ('conadd', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('yaddress', models.CharField(max_length=200)),
                ('ycity', models.CharField(max_length=200)),
                ('yzip', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
