# Generated by Django 4.1.1 on 2022-11-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0011_marriage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriage',
            old_name='capacity',
            new_name='capacity1',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='city',
            new_name='city1',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='hall',
            new_name='hall1',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='halladd',
            new_name='halladd1',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='phno',
            new_name='phno1',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='pricepe',
            new_name='pricepe1',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='zip',
            new_name='zip1',
        ),
    ]
