# Generated by Django 4.1.1 on 2022-11-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0012_rename_capacity_marriage_capacity1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cat',
        ),
    ]
