# Generated by Django 4.1.1 on 2022-11-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0014_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='marriage',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
        migrations.DeleteModel(
            name='music',
        ),
    ]
