# Generated by Django 4.1.1 on 2022-11-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0015_delete_marriage_delete_movie_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('hall1', models.CharField(max_length=200)),
                ('halladd1', models.CharField(max_length=200)),
                ('city1', models.CharField(max_length=200)),
                ('zip1', models.CharField(max_length=200)),
                ('pricepe1', models.CharField(max_length=200)),
                ('capacity1', models.CharField(max_length=200)),
                ('phno1', models.CharField(max_length=200)),
                ('email1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('business', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('thadd', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('yaddress', models.CharField(max_length=200)),
                ('ycity', models.CharField(max_length=200)),
                ('yzip', models.CharField(max_length=200)),
                ('phnum', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('conname', models.CharField(max_length=200)),
                ('nameor', models.CharField(max_length=200)),
                ('conadd', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('yaddress', models.CharField(max_length=200)),
                ('ycity', models.CharField(max_length=200)),
                ('yzip', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
