# Generated by Django 4.1.1 on 2022-12-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0017_contactf'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('theatrename', models.CharField(max_length=200)),
                ('moviename', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('theatreaddress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
            ],
        ),
    ]
