# Generated by Django 4.1.1 on 2022-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0019_dcontactf'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Typeofevent', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('isfood', models.CharField(max_length=200)),
            ],
        ),
    ]
