# Generated by Django 4.1.1 on 2022-12-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0020_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addmovies',
        ),
    ]
