# Generated by Django 4.1.1 on 2022-12-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0025_addmovies2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmovies2',
            name='username',
        ),
    ]
