# Generated by Django 4.1.1 on 2022-12-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0027_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
