# Generated by Django 4.1.1 on 2022-12-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0029_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
