# Generated by Django 4.1.1 on 2022-12-05 07:28

from django.db import migrations, models
import sdp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0030_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('mname', models.CharField(max_length=191)),
                ('genre', models.CharField(max_length=191)),
                ('thaddress', models.CharField(max_length=500, null=True)),
                ('capacity', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=sdp.models.filepath)),
                ('video', models.FileField(blank=True, null=True, upload_to=sdp.models.filepath)),
            ],
        ),
    ]
